### ISSUE TITLE
tsiclient.js:17 Error: <rect> attribute height: A negative value is not valid. ("-11")

### ISSUE THREAD

**Issue by Caitlin-Finn** [microsoft/tsiclient#130]
Upon graph generation the following console error is present:
tsiclient.js:17 Error: <rect> attribute height: A negative value is not valid. ("-11")

**Comment by darsney** [comment]
this is likely due to the fact that you have placed the chart in a container that has no height...try creating a fixed height/width container.  if you have a stable repro feel free to send it as a codepen.  as a rule, yes the sdk should not throw, but i think the error is reasonable (albeit somewhat cryptic) if the container does in fact have no height

**Comment by darsney** [comment]
I'm gonna go ahead and close this.  Here is a codepen with a little example of how you can embed the chart in a flexy container...complete with a working hamburger button on the left nav!

https://codepen.io/darsney/pen/OKZRgP
