### ISSUE TITLE
Proper TSIClient example with msal.js (using up-to-date libraries)

### ISSUE THREAD

**Issue by codemaster3000** [microsoft/tsiclient#292]
I see that every example for this library is using the adal.js library which is marked as deprecated. I want to evaluate if tsiclient.js is a good option to connect with our azure b2c time series db. Maybe it is the only option anyway.

Now for a start, a proper basic example with the recommended libraries like msal.js would help alot. Another Problem is the authentification documentation seems to focus only on C# and is about using the "client secret" which i do not find in the msal.js documentation (again no examples how to use it). The same Problem: The C# Documentation for msal.net is used for the main manual for msal.js. It is a mess :)

**Comment by darsney** [comment]
msal.js works much in the same way as adal.js (give it an appID, give it some scopes, etc etc).  A guide to migrating from adal.js to msal.js can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-compare-msal-js-and-adal-js).  If you apply that to the authentication code that uses adal.js in the examples we've shown, it should work just fine with msal.js.  I use both adal.js and msal.js regularly depending on context, and they are fairly easy to switch between

But as you'll see from the examples, the setup of authentication is actually external to this library.  The tsiclient library just takes an access token for the TSI API, which can be obtained in any number of ways.  I used adal.js in the examples because it was the recommended client side auth library for AAD at the time.  Since it just uses a bunch of vanilla OAuth2 mechanisms, it still works for the purpose it serves in these examples...which is to illustrate the usage of tsiclient, not to be a resource for client side AAD auth libraries

If you believe the documentation for msal is incorrect or misleading, I would follow up in that repository.  Regardless, I don't believe that illustrating the usage of msal.js for a generic web app is something that needs to be done in this repo, and the usage of msal.js (or any other auth library) is also external to whether or not you should use tsiclient.js, so I am going to close this issue
