### ISSUE TITLE
Barchart showing data in a period of time 

### ISSUE THREAD

**Issue by felipebayres** [microsoft/tsiclient#329]
I´m using TSI UX to show some data in graphs from Time Series Insight Explorer but there is a graph that measures energy consumption, and it is more intuitive if the data is shown in a bar from each specific period of time( days , months , maybe years). Like the example below
![image](https://user-images.githubusercontent.com/29110284/121029576-14487900-c77f-11eb-930a-613798ef5f5d.png)

As I saw, Barcharts only  have a slider to step through the timestamps of the supplied time series and it can´t show every data at once, or am I wrong?

**Comment by darsney** [comment]
you aren't wrong, this type of layout is not supported for bar charts.  we know that people want it, we just haven't built it.  the best way to do this would be to make datagroups that represent the months, and series that represent the channels, and have 1 timestamp.  the tooltip would still be ugly because it would show the timestamp, but you could hide the timestamp in the tooltip using CSS.  but you probably just want to use a different chart for this instead of hacking the tsiclient chartDataShape to be completely honest.  

sorry about that!  feedback well taken though, we definitely know folks like this layout for bar charts haha
